### ISSUE TITLE
Send signed transactions through bnsapi

### ISSUE THREAD

**Issue by annatorok** [iov-one/bns#48]
We just got word that Cosmostation would like to be able to submit signed transactions through the bnsapi.  Adding that functionality is top priority list.

**Comment by orkunkl** [comment]
Should we invalidate the tx signature in bnsapi or just proxy the tx request to tendermint?

**Comment by davepuchyr** [comment]
Good question.  Just proxy the signed tx.

**Comment by orkunkl** [comment]
I've some made progress on the PR above. Currently we cannot just post a transaction in json format and marshal it back to  `bnsd.Tx`.
The reason is:
```proto
message PublicKey {
  oneof pub {
    bytes ed25519 = 1;
  }
}
```
crypto/codec uses `oneof` proto directive and this code is generic: json tag is not available in generated go code. [link to the code](http://github.com/iov-one/weave/blob/0c14afa6d500b1fa8eab55f54f53755cabcd7dc2/crypto/models.proto#L5-L9)

Solution I come up with: external parties can generate, sign tx and convert it to hex and submit it to the `tx/submit` api. And this data will be posted to tendermint rpc with correct encoding. I was able to generate a tx and get the hex correspondent of the tx by using a modified version of bnscli: see [branch](https://github.com/iov-one/weave/tree/print-out-tx-as-hex)

Example command to generate tx:

```bash
bnscli send-tokens  -src D5C41DDF386EA9C2963FEC37930DBFB32F832FF3 -dst 569782de1d01cef924c1e546d664cf63c8c0c323 -amount "0.4IOV" | bnscli with-fee -amount "1IOV" | bnscli sign -key $FAUCET | bnscli view
```

The hex tx generated by this command: 

```0a091a0708011a03494f5612681a220a206514e39ee90c1447657175655ab5918c261016e1200db6a216db144ac3076eb222420a4099ec2c9e18b4fa5d831e5e60781a81ad96c223e8aaa133fb323674277adc9a259bdfb9152840517460af9c15d860c65fb66a2e22a9dda31026aa15300a83c90d9a033d0a0208011214d5c41ddf386ea9c2963fec37930dbfb32f832ff31a14569782de1d01cef924c1e546d664cf63c8c0c323220b108088debe011a03494f56```

When I post this tx to the bnsapi with POST request it gets rejected by tendermint CheckTx with error: 
```json
{
	"code": 2,
	"data": "",
	"log": "cannot check tx: cannot verify signatures: invalid signature: unauthorized",
	"hash": "636118A4946D78C0326D44D55C810F8BFB97286683247C00B7EA57466AB3A91A"
}
```

Related tendermint documentation: https://docs.tendermint.com/master/tendermint-core/using-tendermint.html#formatting

**Comment by orkunkl** [comment]
I've some made progress on the PR above. Currently we cannot just post a transaction in json format and marshal it back to  `bnsd.Tx`.
The reason is:
```proto
message PublicKey {
  oneof pub {
    bytes ed25519 = 1;
  }
}
```
crypto/codec uses `oneof` proto directive and this code is generic: json tag is not available in generated go code. [link to the code](http://github.com/iov-one/weave/blob/0c14afa6d500b1fa8eab55f54f53755cabcd7dc2/crypto/models.proto#L5-L9)

Solution I come up with: external parties can generate, sign tx and convert it to hex and submit it to the `tx/submit` api. And this data will be posted to tendermint rpc with correct encoding. I was able to generate a tx and get the hex correspondent of the tx by using a modified version of bnscli: see [branch](https://github.com/iov-one/weave/tree/print-out-tx-as-hex)

Example command to generate tx:

```bash
bnscli send-tokens  -src D5C41DDF386EA9C2963FEC37930DBFB32F832FF3 -dst 569782de1d01cef924c1e546d664cf63c8c0c323 -amount "0.4IOV" | bnscli with-fee -amount "1IOV" | bnscli sign -key $FAUCET | bnscli view
```

The hex tx generated by this command: 

```0a091a0708011a03494f5612681a220a206514e39ee90c1447657175655ab5918c261016e1200db6a216db144ac3076eb222420a4099ec2c9e18b4fa5d831e5e60781a81ad96c223e8aaa133fb323674277adc9a259bdfb9152840517460af9c15d860c65fb66a2e22a9dda31026aa15300a83c90d9a033d0a0208011214d5c41ddf386ea9c2963fec37930dbfb32f832ff31a14569782de1d01cef924c1e546d664cf63c8c0c323220b108088debe011a03494f56```

When I post this tx to the bnsapi with POST request it gets rejected by tendermint CheckTx with error: 
```json
{
	"code": 2,
	"data": "",
	"log": "cannot check tx: cannot verify signatures: invalid signature: unauthorized",
	"hash": "636118A4946D78C0326D44D55C810F8BFB97286683247C00B7EA57466AB3A91A"
}
```

Related tendermint documentation: https://docs.tendermint.com/master/tendermint-core/using-tendermint.html#formatting
